"""Module to store functions about local parsers arguments."""
import argparse

def local_parses():
    """Function to create and return all the local parsers arguments.

    Returns
    -------
    argparse
        Object with parsers and its values.
    """    
    parser = argparse.ArgumentParser(description='Execute taxam.', usage='python ./mappingCoverter ',)

    parser.add_argument('-mp', '--mapping_path', help = 'Folder where are the files to be converted.', type = str, action = 'store', default = None)

    parser.add_argument('-op', '--output_name', help = 'Name of output files.', type = str, action = 'store', default = None)

    parser.add_argument('-ms', '--mapping_sep', help = 'Separator used to part each collumn in mapping file.', type = str, action = 'store', default = '\t')

    parser.add_argument('-os', '--output_sep', help = 'Separator used to part each collumn in output file generated by mappingConverter.', type = str, action = 'store', default = '\t')

    return parser.parse_args()